if (typeof importScripts === "function") importScripts("nimsRestApi.js");
const DEFAULT_HELPER="http://127.0.0.1:8765",DASHBOARD_URL_PATTERN="https://nims-results-cockpit-ne5nig.v2.appdeploy.ai/*",NIMS_LOGIN_URL="https://www.nimsts.edu.in/AHIMSG5/hissso/loginLogin.action";
const NIMS_TAB_PATTERNS=["https://nimsts.edu.in/AHIMSG5/*","https://www.nimsts.edu.in/AHIMSG5/*","https://nimsts.edu.in/HISInvestigationG5/*","https://www.nimsts.edu.in/HISInvestigationG5/*","https://nimsts.edu.in/hislogin/*","https://www.nimsts.edu.in/hislogin/*"];
let dashboardLoginWindowId=null,dashboardHostWindowId=null,dashboardWorkerTabId=null;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function arrayBufferToBase64(buffer){let binary="";for(const b of new Uint8Array(buffer))binary+=String.fromCharCode(b);return btoa(binary);}
function hasReportValues(t){return /\b(?:result|hemoglobin|haemoglobin|wbc|tlc|platelet|creatinine|urea|sodium|potassium|bilirubin|sgot|sgpt|crp|procalcitonin|culture|organism|sensitive|resistant|no growth)\b/i.test(t)&&/\d/.test(t);}
function classifyReportResponse(buffer,contentType,status){const n=buffer?buffer.byteLength:0,c=String(contentType||"").toLowerCase();if(!buffer||!n)return"empty_response";const b=new Uint8Array(buffer.slice(0,5));if(c.includes("application/pdf")||(b[0]===37&&b[1]===80&&b[2]===68&&b[3]===70))return"pdf_report";if(!c.includes("text/html")&&!c.includes("text/plain"))return"unsupported_content_type";const t=new TextDecoder("utf-8").decode(buffer.slice(0,50000)).toLowerCase();if(/\b(login|session expired|session has expired|authentication|captcha|otp|sign in|password)\b/.test(t))return"html_login_or_session";if(/duplicate\s+result\s+report/.test(t))return"html_duplicate_report_page";if(/<(?:iframe|embed|object)\b|pdfviewer|viewer|window\.print/.test(t)&&!hasReportValues(t))return"html_report_viewer";if(c.includes("text/plain")||hasReportValues(t))return c.includes("text/html")?"html_report_content":"text_report";if([404,405,500].includes(Number(status)))return"wrong_endpoint";return"html_unrecognized_report_candidate";}
function classificationError(c){if(["pdf_report","text_report","html_report_content"].includes(c))return"";if(c==="html_login_or_session")return"NIMS session expired or authentication is required.";if(c==="empty_response")return"NIMS returned an empty report response.";return"NIMS returned unsupported report content.";}
async function callHelper(path,options={}){try{const r=await fetch(DEFAULT_HELPER+path,options),txt=await r.text();let data=null;try{data=txt?JSON.parse(txt):null;}catch{data=txt;}return r.ok?{ok:true,data}:{ok:false,error:"Local parser returned status "+r.status,data};}catch(e){return{ok:false,error:"Local parser is not reachable at 127.0.0.1:8765. Start it and retry. Details: "+(e&&e.message?e.message:"connection failed")};}}
async function ensureHelper(){const h=await callHelper("/health");if(!h.ok||!h.data||h.data.ok!==true)throw new Error(h.error||"Local NIMS parser is unavailable.");}
async function pushDashboardEvent(eventType,payload){const tabs=await chrome.tabs.query({url:[DASHBOARD_URL_PATTERN]}).catch(()=>[]);await Promise.all(tabs.map(t=>t.id?chrome.tabs.sendMessage(t.id,{type:"NIMS_DASHBOARD_EVENT",eventType,payload:payload||{}}).catch(()=>{}):Promise.resolve()));}
async function handleDashboardSessionState(state,sender){const tab=sender&&sender.tab;if(!tab||!tab.id||!state||!state.authenticated)return;dashboardWorkerTabId=tab.id;if(dashboardLoginWindowId&&tab.windowId===dashboardLoginWindowId&&dashboardHostWindowId){try{await chrome.tabs.move(tab.id,{windowId:dashboardHostWindowId,index:-1});await chrome.tabs.update(tab.id,{active:false});}catch{}try{await chrome.windows.remove(dashboardLoginWindowId);}catch{}dashboardLoginWindowId=null;}await pushDashboardEvent("KBP_NIMS_STATUS",{ok:true,loggedIn:true,state:"logged_in"});}
async function frameIdsForTab(tabId){const f=await chrome.webNavigation.getAllFrames({tabId}).catch(()=>[]);const ids=f.map(x=>x.frameId);return ids.length?ids:[0];}
async function messageFrames(tabId,message){const out=[];for(const frameId of await frameIdsForTab(tabId)){try{const r=await chrome.tabs.sendMessage(tabId,message,{frameId});if(r)out.push({frameId,response:r});}catch{}}return out;}
async function probeNimsTab(tabId){const states=(await messageFrames(tabId,{type:"NIMS_BRIDGE_PROBE"})).map(x=>({frameId:x.frameId,...(x.response.state||{})}));return{authenticated:states.some(s=>s.authenticated),crFrame:states.find(s=>s.crFieldReady)||null,reportFrame:states.find(s=>Number(s.reportRows||0)>0)||null};}
async function getDashboardSessionStatus(){for(const tab of await chrome.tabs.query({url:NIMS_TAB_PATTERNS}).catch(()=>[])){if(!tab.id)continue;const p=await probeNimsTab(tab.id);if(p.authenticated){dashboardWorkerTabId=tab.id;return{ok:true,loggedIn:true,state:"logged_in"};}}return{ok:true,loggedIn:false,state:dashboardLoginWindowId?"signing_in":"logged_out"};}
async function openDashboardLogin(sender){const current=await getDashboardSessionStatus();if(current.loggedIn)return current;dashboardHostWindowId=sender&&sender.tab?sender.tab.windowId:null;if(dashboardLoginWindowId){try{await chrome.windows.update(dashboardLoginWindowId,{focused:true});return{ok:true,loggedIn:false,state:"signing_in"};}catch{dashboardLoginWindowId=null;}}const w=await chrome.windows.create({url:NIMS_LOGIN_URL,type:"popup",width:1160,height:820,focused:true});dashboardLoginWindowId=w.id||null;await pushDashboardEvent("KBP_NIMS_STATUS",{ok:true,loggedIn:false,state:"signing_in"});return{ok:true,loggedIn:false,state:"signing_in"};}
async function waitForTabComplete(tabId,timeout=15000){const start=Date.now();while(Date.now()-start<timeout){try{if((await chrome.tabs.get(tabId)).status==="complete")return true;}catch{return false;}await delay(250);}return false;}
async function ensureDashboardWorkerTab(){if(dashboardWorkerTabId){try{await chrome.tabs.get(dashboardWorkerTabId);if((await probeNimsTab(dashboardWorkerTabId)).authenticated)return dashboardWorkerTabId;}catch{}}const s=await getDashboardSessionStatus();if(s.loggedIn&&dashboardWorkerTabId)return dashboardWorkerTabId;const t=await chrome.tabs.create({url:NIMS_LOGIN_URL,active:false});if(!t.id)throw new Error("Unable to open the NIMS session.");dashboardWorkerTabId=t.id;await waitForTabComplete(t.id);for(let i=0;i<20;i++){if((await probeNimsTab(t.id)).authenticated)return t.id;await delay(350);}throw new Error("NIMS session is not authenticated. Sign in again.");}
async function findCrFrame(tabId){for(let a=0;a<18;a++){const p=await probeNimsTab(tabId);if(p.crFrame)return p.crFrame.frameId;for(const frameId of [0,...(await frameIdsForTab(tabId)).filter(x=>x!==0)]){try{const r=await chrome.tabs.sendMessage(tabId,{type:"NIMS_BRIDGE_OPEN_CR"},{frameId});if(r&&r.ok)break;}catch{}}await delay(a<5?550:900);}throw new Error("Unable to open the NIMS CR-wise results page.");}
async function waitForReportFrame(tabId){for(let a=0;a<30;a++){const p=await probeNimsTab(tabId);if(p.reportFrame)return p.reportFrame.frameId;await delay(500);}throw new Error("NIMS did not return a result list for this CR number.");}
function cultureNarrative(c){if(!c)return"";const organisms=Array.isArray(c.organisms)&&c.organisms.length?c.organisms.join(", "):String(c.organism||"");return[c.site_specimen||c.site||c.specimen||"",c.result||c.result_status||"",organisms,c.growth_quantity||"",c.comment||"",Array.isArray(c.susceptible_antibiotics)&&c.susceptible_antibiotics.length?"Susceptible: "+c.susceptible_antibiotics.join(", "):"",Array.isArray(c.resistant_antibiotics)&&c.resistant_antibiotics.length?"Resistant: "+c.resistant_antibiotics.join(", "):""].filter(Boolean).join(" · ");}
function bundleFromParsedReports(crNo,patient,sourceReports,parsedReports,source,listedCount){const results=[];let i=0;for(const report of parsedReports){for(const p of report.parameters||[])results.push({id:"nims-"+(++i),group:report.report_type||(report.report_tags||[]).join(", "),test:report.report_name||p.name||"Investigation",parameter:p.canonical_name||p.name||"Result",date:p.date_sent||report.date_sent||"",value:p.value==null?"":String(p.value),unit:p.unit||"",refRange:p.reference_range||"",abnormal:p.abnormal_flag||"unknown",reportId:report.report_id||""});const cultures=[];if(report.culture)cultures.push(report.culture);if(Array.isArray(report.culture_results))cultures.push(...report.culture_results);for(const c of cultures){const value=cultureNarrative(c);if(value)results.push({id:"nims-"+(++i),group:"Microbiology",test:report.report_name||"Culture",parameter:"Culture result",date:c.reporting_date||c.collection_date||c.date_sent||report.date_sent||"",value,reportId:report.report_id||""});}}return{schemaVersion:"nims-dashboard-canonical-v1",patient:{name:patient&&patient.name?patient.name:"",crNo:patient&&patient.crNo?patient.crNo:crNo},source,coverage:{resultCount:results.length,reportCount:Number(listedCount||sourceReports.length),parsedReportCount:parsedReports.length},reports:sourceReports,results,enquiryRows:[]};}
async function parseFetchedReport(report,url){const r=await fetch(url,{method:"GET",credentials:"include",redirect:"follow"}),ctype=r.headers.get("content-type")||"",buffer=await r.arrayBuffer(),reason=classificationError(classifyReportResponse(buffer,ctype,r.status));if(!r.ok||reason)return{ok:false,error:reason||"NIMS report request failed."};const p=await callHelper("/parse-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({report_id:report.id||"",report_name:report.title||"Investigation report",date_sent:report.date||"",content_type:ctype,pdf_base64:arrayBufferToBase64(buffer)})});if(!p.ok||!p.data)return{ok:false,error:p.error||"Local parser failed."};return{ok:true,parsed:p.data};}
async function parseUsableReports(reports){const parsedReports=[],sourceReports=[];for(const report of reports){try{const url=self.NimsRestApi&&self.NimsRestApi.safeReportUrl?self.NimsRestApi.safeReportUrl(report.resolvedUrl||report.url||""):"";if(!url)continue;const r=await parseFetchedReport(report,url);if(!r.ok)continue;parsedReports.push(r.parsed);sourceReports.push({id:report.id||"",title:report.title||"Investigation report",date:report.date||"",department:report.department||""});}catch{}}return{parsedReports,sourceReports};}
async function tryRestApiForDashboard(crNo){if(!self.NimsRestApi)return{ok:false,reason:"REST adapter unavailable."};try{const list=await self.NimsRestApi.fetchReportList(crNo,fetch,"33101"),diagnostics=self.NimsRestApi.safeDiagnostics(list),usable=list.reports.map(r=>({...r,resolvedUrl:r.url||self.NimsRestApi.verifiedReportUrlForToken(r.token)})).filter(r=>r.resolvedUrl);if(!usable.length)return{ok:false,reason:"REST report rows expose neither a verified report URL nor a safe report token.",diagnostics};const parsed=await parseUsableReports(usable),bundle=bundleFromParsedReports(crNo,{name:list.patientName||"",crNo:list.returnedCrNo||crNo},parsed.sourceReports,parsed.parsedReports,"nims_rest_api",list.reports.length);if(!bundle.results.length)return{ok:false,reason:"REST reports produced no structured result values.",diagnostics};return{ok:true,bundle,diagnostics};}catch(e){return{ok:false,reason:e&&e.message?e.message:"NIMS REST retrieval failed.",code:e&&e.code?e.code:""};}}
async function fetchCrForDashboardLegacy(crNo){const tabId=await ensureDashboardWorkerTab(),frameId=await findCrFrame(tabId),submitted=await chrome.tabs.sendMessage(tabId,{type:"NIMS_BRIDGE_SUBMIT_CR",crNo},{frameId});if(!submitted||submitted.ok===false)throw new Error(submitted&&submitted.error||"Unable to submit CR number.");const reportFrameId=await waitForReportFrame(tabId),extracted=await chrome.tabs.sendMessage(tabId,{type:"NIMS_BRIDGE_EXTRACT_DASHBOARD_DATA"},{frameId:reportFrameId});if(!extracted||extracted.ok===false)throw new Error(extracted&&extracted.error||"Unable to read the NIMS result list.");const returnedCr=String(extracted.patient&&extracted.patient.crNo||"").replace(/\D/g,"");if(returnedCr&&returnedCr!==crNo)throw new Error("NIMS identity verification failed. Results were not retrieved.");const usable=(extracted.reports||[]).map(r=>({...r,resolvedUrl:r.url||""})).filter(r=>r.resolvedUrl);if(!usable.length)throw new Error("The NIMS result list did not expose any verified report links.");const parsed=await parseUsableReports(usable),bundle=bundleFromParsedReports(crNo,extracted.patient||{crNo},parsed.sourceReports,parsed.parsedReports,"authenticated_browser_fallback",extracted.reportCount||extracted.reports.length);if(!bundle.results.length)throw new Error("The browser fallback found reports but produced no structured result values.");return bundle;}
async function fetchCrForDashboard(raw){const crNo=String(raw||"").replace(/\D/g,"");if(!/^\d{15}$/.test(crNo))return{ok:false,error:"Enter the 15-digit NIMS CR number."};try{await pushDashboardEvent("KBP_NIMS_FETCH_STARTED",{preferredSource:"nims_rest_api"});await ensureDashboardWorkerTab();await ensureHelper();const rest=await tryRestApiForDashboard(crNo);if(!rest.ok&&rest.code==="NIMS_IDENTITY_MISMATCH")throw new Error("NIMS identity verification failed. Results were not retrieved.");let bundle;if(rest.ok)bundle=rest.bundle;else{await pushDashboardEvent("KBP_NIMS_SOURCE_FALLBACK",{from:"nims_rest_api",to:"authenticated_browser_fallback",reason:rest.reason||"REST path unavailable.",diagnostics:rest.diagnostics||{}});bundle=await fetchCrForDashboardLegacy(crNo);}await pushDashboardEvent("KBP_NIMS_BULK_RESULTS",{payload:bundle});return{ok:true,source:bundle.source,resultCount:bundle.results.length,reportCount:bundle.reports.length};}catch(e){const error=e&&e.message?e.message:"NIMS retrieval failed.";await pushDashboardEvent("KBP_NIMS_FETCH_ERROR",{error});return{ok:false,error};}}
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(!message)return false;if(message.type==="NIMS_SESSION_STATE"){handleDashboardSessionState(message.state||{},sender).then(()=>sendResponse({ok:true}));return true;}if(message.type==="NIMS_DASHBOARD_STATUS"){getDashboardSessionStatus().then(sendResponse);return true;}if(message.type==="NIMS_DASHBOARD_LOGIN"){openDashboardLogin(sender).then(sendResponse);return true;}if(message.type==="NIMS_DASHBOARD_FETCH_CR"){fetchCrForDashboard(message.crNo).then(sendResponse);return true;}return false;});