import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const manifest=JSON.parse(fs.readFileSync(new URL('../manifest.json',import.meta.url),'utf8'));
const dashboardBridge=fs.readFileSync(new URL('../src/dashboardBridge.js',import.meta.url),'utf8');
const sessionBridge=fs.readFileSync(new URL('../src/nimsSessionBridge.js',import.meta.url),'utf8');
const background=fs.readFileSync(new URL('../src/background.js',import.meta.url),'utf8');
test('manifest is results-only',()=>{assert.equal(manifest.version,'0.5.0');assert.deepEqual(manifest.permissions.sort(),['tabs','webNavigation'].sort());assert.equal(manifest.side_panel,undefined);assert.equal(manifest.action,undefined);const n=manifest.content_scripts.find(e=>e.matches.some(m=>m.includes('nimsts.edu.in')));assert.deepEqual(n.js,['src/navigationCore.js','src/nimsSessionBridge.js']);});
test('bridge contracts and runtime version remain',()=>{for(const t of ['KBP_NIMS_STATUS_REQUEST','KBP_NIMS_LOGIN_REQUEST','KBP_NIMS_FETCH_REQUEST','KBP_NIMS_BULK_RESULTS'])assert.match(dashboardBridge+background,new RegExp(t));assert.match(dashboardBridge,/chrome\.runtime\.getManifest\(\)\.version/);});
test('REST is primary and browser is explicit fallback',()=>{const start=background.indexOf('async function fetchCrForDashboard(raw)');const b=background.slice(start);assert.ok(start>=0);assert.ok(b.indexOf('tryRestApiForDashboard')>=0);assert.ok(b.indexOf('tryRestApiForDashboard')<b.indexOf('fetchCrForDashboardLegacy'));assert.match(b,/KBP_NIMS_SOURCE_FALLBACK/);});
test('identity mismatch fails closed',()=>{assert.match(background,/NIMS_IDENTITY_MISMATCH/);assert.match(background,/returnedCr&&returnedCr!==crNo/);});
test('legacy mapping and UI machinery are gone',()=>{for(const t of ['NIMS_BRIDGE_RUN_SUMMARY','NIMS_DISCOVER_MAPPING','NIMS_GET_MAPPING_SUMMARY','chrome.webRequest','chrome.scripting','sidePanel'])assert.doesNotMatch(background,new RegExp(t));});
test('transient URLs stay fetch-only',()=>{const start=background.indexOf('async function parseUsableReports'),end=background.indexOf('async function tryRestApiForDashboard',start),b=background.slice(start,end);assert.match(b,/parseFetchedReport\(report,url\)/);assert.doesNotMatch(b,/sourceReports\.push\([^]*url:/);});
test('session bridge has no persistence or summary path',()=>{assert.doesNotMatch(sessionBridge,/chrome\.storage/);assert.doesNotMatch(sessionBridge,/NIMS_BRIDGE_RUN_SUMMARY/);assert.match(sessionBridge,/NIMS_BRIDGE_EXTRACT_DASHBOARD_DATA/);});
test('scripts compile',()=>{assert.doesNotThrow(()=>new Function(dashboardBridge));assert.doesNotThrow(()=>new Function(sessionBridge));assert.doesNotThrow(()=>new Function(background));});