name: Android compile bare
on: pull_request
permissions:
  contents: read
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Compile branch
        run: |
          git clone --quiet --depth 1 --branch runtime-direct-v082 "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" source
          cd source/mobile/android
          ./gradlew compileDebugKotlin --quiet
